-- Q16: our ThalamusDB formulation of swan_queries/Q16.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE b_base AS SELECT l.l_orderkey, l.l_linenumber, l.l_partkey, l.l_suppkey, l.l_quantity, l.l_extendedprice, l.l_discount, l.l_shipmode, l.l_shipinstruct, o.o_orderdate, o.o_orderpriority, o.o_totalprice FROM lineitem l JOIN orders o ON o.o_orderkey = l.l_orderkey WHERE l.l_shipdate >= DATE '1995-01-01' AND l.l_shipdate < DATE '1997-01-01' AND l.l_discount BETWEEN 0.05 AND 0.07 AND l.l_quantity BETWEEN 18 AND 22 AND l.l_shipmode IN ('AIR', 'REG AIR') AND l.l_shipinstruct = 'DELIVER IN PERSON' AND o.o_orderstatus = 'O' AND o.o_orderpriority IN ('1-URGENT', '2-HIGH') AND o.o_totalprice > 100000;
CREATE TABLE part_src AS SELECT p_partkey, p_name, p_type, p_brand, 'Part Name: ' || coalesce(CAST(p_name AS VARCHAR), '') || E'\n' || 'Part Type: ' || coalesce(CAST(p_type AS VARCHAR), '') || E'\n' || 'Brand: ' || coalesce(CAST(p_brand AS VARCHAR), '') AS item_part_src FROM part;
CREATE TABLE customer_src AS SELECT *, 'Customer Name: ' || coalesce(CAST(c_name AS VARCHAR), '') || E'\n' || 'Market Segment: ' || coalesce(CAST(c_mktsegment AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(c_acctbal AS VARCHAR), '') AS item_customer_src FROM (SELECT * FROM customer LIMIT 100);
SELECT part_src.p_partkey, part_src.p_name, part_src.p_type, part_src.p_brand, b.l_orderkey, b.l_linenumber, b.l_suppkey, b.l_quantity, b.l_extendedprice, b.l_discount, b.l_shipmode, b.l_shipinstruct, b.o_orderdate, b.o_orderpriority, b.o_totalprice, customer_src.c_custkey, customer_src.c_name, customer_src.c_address, customer_src.c_nationkey, customer_src.c_phone, customer_src.c_acctbal, customer_src.c_mktsegment, customer_src.c_comment FROM part_src JOIN b_base b ON b.l_partkey = part_src.p_partkey, customer_src WHERE NLfilter(part_src.item_part_src, 'Task: classify whether this part should be included in customer-facing demand analysis. Rule: YES only if the part sounds like a finished good that could appear in commercial product demand; NO for raw/industrial-looking components. If uncertain, answer NO.') AND NLfilter(customer_src.item_customer_src, 'Task: decide if this is an enterprise-oriented customer profile for B2B order analysis. Rule: YES only for profiles that look commercially active (business segment + meaningful balance); otherwise NO. If uncertain, answer NO.') AND NLfilter(customer_src.item_customer_src, 'You are validating whether this customer profile is a business-relevant account for enterprise analysis. If uncertain, answer NO.');
