-- Q17: our ThalamusDB formulation of swan_queries/Q17.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE orders_src AS SELECT o.*, 'Order Priority: ' || coalesce(CAST(o.o_orderpriority AS VARCHAR), '') || E'\n' || 'Total Price: ' || coalesce(CAST(o.o_totalprice AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(o.o_comment AS VARCHAR), '') AS item_orders_src FROM orders o WHERE o.o_orderdate >= DATE '1993-01-01' AND o.o_orderdate < DATE '1997-01-01' AND o.o_orderstatus IN ('O', 'F') AND o.o_totalprice > 50000;
CREATE TABLE lineitem_focus AS SELECT l.l_orderkey, l.l_partkey, l.l_suppkey, l.l_shipmode, l.l_shipinstruct, l.l_quantity, l.l_extendedprice, l.l_discount, l.l_tax, l.l_returnflag FROM lineitem l WHERE l.l_shipdate >= DATE '1993-01-01' AND l.l_shipdate < DATE '1998-01-01' AND l.l_quantity BETWEEN 5 AND 40 AND l.l_discount BETWEEN 0.01 AND 0.10 AND l.l_shipmode IN ('AIR', 'REG AIR', 'TRUCK');
CREATE TABLE part_supplier AS SELECT p.p_partkey, p.p_name, p.p_type, p.p_brand, s.s_suppkey, s.s_name, n.n_name AS supplier_nation FROM part p JOIN partsupp ps ON ps.ps_partkey = p.p_partkey JOIN supplier s ON s.s_suppkey = ps.ps_suppkey JOIN nation n ON n.n_nationkey = s.s_nationkey WHERE p.p_size BETWEEN 5 AND 35 AND ps.ps_supplycost BETWEEN 10 AND 1000;
CREATE TABLE customer_src AS SELECT *, 'Customer Name: ' || coalesce(CAST(c_name AS VARCHAR), '') || E'\n' || 'Market Segment: ' || coalesce(CAST(c_mktsegment AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(c_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(c_comment AS VARCHAR), '') AS item_customer_src FROM (SELECT * FROM customer LIMIT 120);
CREATE TABLE orders_sem AS SELECT * FROM orders_src WHERE NLfilter(orders_src.item_orders_src, 'You are triaging enterprise orders for operations monitoring. From the priority label, total price, and order comment, does this order look important enough to deserve active follow-up by an operations manager? If uncertain, answer YES.');
CREATE TABLE customer_sem AS SELECT * FROM customer_src WHERE NLfilter(customer_src.item_customer_src, 'You are identifying high-value B2B customer profiles. From the customer name format, market segment, balance, and account comment, does this record look like a customer worth prioritizing in business account analytics? If uncertain, answer NO.') AND NLfilter(customer_src.item_customer_src, 'You are an operations manager assessing whether a high-value customer is associated with an important order that requires active follow-up.');
SELECT orders_sem.o_orderkey, orders_sem.o_custkey, orders_sem.o_orderdate, orders_sem.o_orderpriority, orders_sem.o_totalprice, lf.l_partkey, lf.l_suppkey, lf.l_shipmode, lf.l_shipinstruct, lf.l_quantity, lf.l_extendedprice, lf.l_discount, lf.l_tax, lf.l_returnflag, ps.p_name, ps.p_type, ps.p_brand, ps.s_name, ps.supplier_nation, customer_sem.c_custkey, customer_sem.c_name, customer_sem.c_address, customer_sem.c_nationkey, customer_sem.c_phone, customer_sem.c_acctbal, customer_sem.c_mktsegment, customer_sem.c_comment FROM orders_sem JOIN lineitem_focus lf ON lf.l_orderkey = orders_sem.o_orderkey JOIN part_supplier ps ON ps.p_partkey = lf.l_partkey AND ps.s_suppkey = lf.l_suppkey, customer_sem;
