-- Q19: our ThalamusDB formulation of swan_queries/Q19.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE lineitem_src AS SELECT l.*, 'Lineitem shipping details:' || E'\n' || 'Mode: ' || coalesce(CAST(l.l_shipmode AS VARCHAR), '') || E'\n' || 'Instruction: ' || coalesce(CAST(l.l_shipinstruct AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(l.l_comment AS VARCHAR), '') AS item_lineitem_src FROM lineitem l WHERE l.l_shipdate >= DATE '1994-01-01' AND l.l_shipdate < DATE '1998-01-01' AND l.l_returnflag IN ('R', 'A', 'N') AND l.l_quantity BETWEEN 3 AND 38 AND l.l_discount BETWEEN 0.00 AND 0.10;
CREATE TABLE order_customer AS SELECT o.o_orderkey, o.o_custkey, o.o_orderdate, o.o_orderpriority, o.o_orderstatus, o.o_totalprice, c.c_name, c.c_mktsegment, c.c_acctbal, c.c_comment FROM orders o JOIN customer c ON c.c_custkey = o.o_custkey WHERE o.o_orderdate >= DATE '1994-01-01' AND o.o_orderdate < DATE '1998-01-01' AND o.o_orderstatus IN ('O', 'F') AND o.o_totalprice > 20000;
CREATE TABLE part_supplier AS SELECT p.p_partkey, p.p_name, p.p_type, p.p_brand, s.s_suppkey, s.s_name, s.s_acctbal FROM part p JOIN partsupp ps ON ps.ps_partkey = p.p_partkey JOIN supplier s ON s.s_suppkey = ps.ps_suppkey WHERE p.p_size BETWEEN 1 AND 40 AND ps.ps_supplycost BETWEEN 5 AND 1200;
CREATE TABLE customer_src AS SELECT *, 'Customer profile check:' || E'\n' || 'Name: ' || coalesce(CAST(c_name AS VARCHAR), '') || E'\n' || 'Segment: ' || coalesce(CAST(c_mktsegment AS VARCHAR), '') || E'\n' || 'Balance: ' || coalesce(CAST(c_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(c_comment AS VARCHAR), '') AS item_customer_src FROM (SELECT * FROM customer LIMIT 180);
CREATE TABLE lineitem_sem AS SELECT * FROM lineitem_src WHERE NLfilter(lineitem_src.item_lineitem_src, 'Is this likely a potentially problematic fulfillment case worth audit attention? If unsure, answer YES.');
CREATE TABLE customer_sem AS SELECT * FROM customer_src WHERE NLfilter(customer_src.item_customer_src, 'Answer YES only if this customer appears likely to have higher complaint/escalation risk in commercial operations. Otherwise answer NO. If unsure, answer NO.');
SELECT lineitem_sem.l_orderkey, lineitem_sem.l_partkey, lineitem_sem.l_suppkey, lineitem_sem.l_quantity, lineitem_sem.l_extendedprice, lineitem_sem.l_discount, lineitem_sem.l_tax, lineitem_sem.l_returnflag, lineitem_sem.l_linestatus, lineitem_sem.l_shipmode, lineitem_sem.l_shipinstruct, oc.o_orderdate, oc.o_orderpriority, oc.o_orderstatus, oc.o_totalprice, oc.c_name, oc.c_mktsegment, oc.c_acctbal, ps.p_name, ps.p_type, ps.p_brand, ps.s_name, ps.s_acctbal, customer_sem.c_custkey, customer_sem.c_name AS cc_name, customer_sem.c_address, customer_sem.c_nationkey, customer_sem.c_phone, customer_sem.c_acctbal AS cc_acctbal, customer_sem.c_mktsegment AS cc_mktsegment, customer_sem.c_comment FROM lineitem_sem JOIN order_customer oc ON oc.o_orderkey = lineitem_sem.l_orderkey JOIN part_supplier ps ON ps.p_partkey = lineitem_sem.l_partkey AND ps.s_suppkey = lineitem_sem.l_suppkey, customer_sem;
