-- Q22: our ThalamusDB formulation of swan_queries/Q22.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE yelp_business AS SELECT * FROM read_csv_auto('./dataset/yelp/yelp_business_csv/business.csv', maximum_line_size=1048576);
CREATE TABLE yelp_review AS SELECT * FROM read_csv_auto('./dataset/yelp/review.csv', maximum_line_size=1048576);
CREATE TABLE yelp_tip AS SELECT * FROM read_csv_auto('./dataset/yelp/tip.csv', maximum_line_size=1048576);
CREATE TABLE reviews_link AS SELECT 'businessid_' || regexp_extract(r.business_ref, '([0-9]+)$') AS business_id, r.rating, r.date AS review_date FROM yelp_review r WHERE r.business_ref LIKE 'businessref_%';
CREATE TABLE tips_link AS SELECT 'businessid_' || regexp_extract(t.business_ref, '([0-9]+)$') AS business_id, t.date AS tip_date FROM yelp_tip t WHERE t.business_ref LIKE 'businessref_%';
CREATE TABLE yelp_src AS SELECT yb.*, 'Business ID: ' || coalesce(CAST(yb.business_id AS VARCHAR), '') || E'\n' || 'Attributes: ' || coalesce(CAST(yb.attributes AS VARCHAR), '') || E'\n' || 'Description: ' || coalesce(CAST(yb.description AS VARCHAR), '') AS item_yelp_src FROM yelp_business yb;
CREATE TABLE valid_states AS SELECT business_id, state_code FROM (SELECT business_id, regexp_extract(description, ',\s*([A-Z]{2})\b', 1) AS state_code FROM yelp_src) s WHERE state_code IN ('AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY');
SELECT vs.state_code AS state, yelp_src.business_id, rl.review_date, rl.rating FROM valid_states vs JOIN yelp_src ON yelp_src.business_id = vs.business_id JOIN reviews_link rl ON rl.business_id = vs.business_id JOIN tips_link tl ON tl.business_id = vs.business_id WHERE yelp_src.attributes ILIKE '%"WiFi":%' AND rl.review_date ILIKE '%2018%' AND tl.tip_date ILIKE '%2018%' AND NLfilter(yelp_src.item_yelp_src, 'Return true if the business offers public WiFi access for its customers. Use both the attributes and description for evidence.') ORDER BY rl.rating DESC, rl.review_date DESC;
