-- Q23: our ThalamusDB formulation of swan_queries/Q23.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE yelp_business AS SELECT * FROM read_csv_auto('./dataset/yelp/yelp_business_csv/business.csv', maximum_line_size=1048576);
CREATE TABLE yelp_review AS SELECT * FROM read_csv_auto('./dataset/yelp/review.csv', maximum_line_size=1048576);
CREATE TABLE yelp_tip AS SELECT * FROM read_csv_auto('./dataset/yelp/tip.csv', maximum_line_size=1048576);
CREATE TABLE yelp_src AS SELECT yb.*, 'Business ID: ' || coalesce(CAST(yb.business_id AS VARCHAR), '') || E'\n' || 'Name: ' || coalesce(CAST(yb.name AS VARCHAR), '') || E'\n' || 'Attributes: ' || coalesce(CAST(yb.attributes AS VARCHAR), '') || E'\n' || 'Description: ' || coalesce(CAST(yb.description AS VARCHAR), '') AS item_yelp_src FROM yelp_business yb;
CREATE TABLE category_tokens AS SELECT n.business_id, lower(trim(tokens.raw_token)) AS category FROM (SELECT s.business_id, regexp_replace(coalesce(regexp_extract(s.description, '(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+(.+?)(?:\.|$)', 1), ''), '^(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+', '') AS raw_categories FROM yelp_src s) n, LATERAL UNNEST(string_split(replace(replace(replace(n.raw_categories, ', and ', ', '), ' and ', ', '), '  ', ' '), ',')) AS tokens(raw_token) WHERE trim(tokens.raw_token) <> '';
CREATE TABLE reviews_link AS SELECT 'businessid_' || regexp_extract(r.business_ref, '([0-9]+)$') AS business_id, r.rating, COALESCE(try_strptime(r.date, '%Y-%m-%d %H:%M:%S'), try_strptime(r.date, '%d %b %Y, %H:%M'), try_strptime(r.date, '%d %b %Y %H:%M'), try_strptime(r.date, '%d %b %Y, %I:%M %p'), try_strptime(r.date, '%d %B %Y, %H:%M'), try_strptime(r.date, '%d %B %Y, %I:%M %p'), try_strptime(r.date, '%B %d, %Y at %I:%M %p'), try_strptime(r.date, '%B %d, %Y %H:%M %p'), try_strptime(r.date, '%d %B %Y at %I:%M %p'), try_strptime(r.date, '%d %b %Y at %I:%M %p')) AS review_ts FROM yelp_review r WHERE r.business_ref LIKE 'businessref_%';
SELECT yelp_src.name AS business_name, ct.category, rl.review_ts AS review_time, rl.rating FROM yelp_src JOIN reviews_link rl ON rl.business_id = yelp_src.business_id JOIN category_tokens ct ON ct.business_id = yelp_src.business_id WHERE rl.review_ts BETWEEN TIMESTAMP '2016-01-01 00:00:00' AND TIMESTAMP '2016-06-30 23:59:59' AND rl.review_ts IS NOT NULL AND NLfilter(yelp_src.item_yelp_src, 'Return true if the description makes the primary business category explicit (for example, Italian restaurant, dental clinic, yoga studio). Favor entries where you can clearly read at least one category phrase.') ORDER BY rl.rating DESC, rl.review_ts DESC;
