-- Q27: our ThalamusDB formulation of swan_queries/Q27.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE part_src AS SELECT p_partkey, p_name, p_type, p_brand, p_size, 'Part Name: ' || coalesce(CAST(p_name AS VARCHAR), '') || E'\n' || 'Part Type: ' || coalesce(CAST(p_type AS VARCHAR), '') || E'\n' || 'Brand: ' || coalesce(CAST(p_brand AS VARCHAR), '') || E'\n' || 'Size: ' || coalesce(CAST(p_size AS VARCHAR), '') AS item_part_src FROM part;
CREATE TABLE supply_base AS SELECT ps.ps_partkey, ps.ps_suppkey, ps.ps_availqty, ps.ps_supplycost, s.s_name, s.s_acctbal, s.s_comment, s.s_nationkey, n.n_name AS nation_name, r.r_name AS region_name FROM partsupp ps JOIN supplier s ON s.s_suppkey = ps.ps_suppkey JOIN nation n ON n.n_nationkey = s.s_nationkey JOIN region r ON r.r_regionkey = n.n_regionkey WHERE ps.ps_availqty BETWEEN 10 AND 600 AND ps.ps_supplycost BETWEEN 20 AND 900 AND r.r_name IN ('EUROPE', 'ASIA', 'AMERICA');
CREATE TABLE orders_lineitem AS SELECT l.l_partkey, l.l_suppkey, l.l_orderkey, l.l_quantity, l.l_extendedprice, l.l_discount, o.o_orderdate, o.o_orderpriority, o.o_totalprice FROM lineitem l JOIN orders o ON o.o_orderkey = l.l_orderkey WHERE o.o_orderdate >= DATE '1994-01-01' AND o.o_orderdate < DATE '1997-01-01' AND l.l_quantity BETWEEN 8 AND 35 AND l.l_discount BETWEEN 0.00 AND 0.08;
CREATE TABLE part_focus AS SELECT part_src.p_partkey, part_src.p_name, part_src.p_type, part_src.p_brand, part_src.p_size FROM part_src WHERE NLfilter(part_src.item_part_src, 'You are screening parts for strategic sourcing analysis. Looking at part name, type, brand, and size, does this look like a differentiated component where supplier quality and pricing strategy would matter? If uncertain, answer YES.');
CREATE TABLE joined AS SELECT pf.p_partkey, pf.p_name, pf.p_type, pf.p_brand, sb.ps_suppkey, sb.s_name, sb.s_acctbal, sb.s_comment, sb.nation_name, sb.region_name, sb.ps_availqty, sb.ps_supplycost, ol.l_orderkey, ol.l_quantity, ol.l_extendedprice, ol.o_orderdate, ol.o_orderpriority, ol.o_totalprice FROM part_focus pf JOIN supply_base sb ON sb.ps_partkey = pf.p_partkey JOIN orders_lineitem ol ON ol.l_partkey = sb.ps_partkey AND ol.l_suppkey = sb.ps_suppkey;
CREATE TABLE supplier_src AS SELECT s.s_suppkey, s.s_name, s.s_address, s.s_nationkey, s.s_phone, s.s_acctbal, s.s_comment, 'Supplier Name: ' || coalesce(CAST(s.s_name AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(s.s_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(s.s_comment AS VARCHAR), '') AS item_supplier_src FROM supplier s JOIN (SELECT DISTINCT ps_suppkey FROM joined LIMIT 80) k ON k.ps_suppkey = s.s_suppkey;
CREATE TABLE pairs AS SELECT j.*, 'Part Type: ' || coalesce(CAST(j.p_type AS VARCHAR), '') || E'\n' || 'Region: ' || coalesce(CAST(j.region_name AS VARCHAR), '') || E'\n' || 'Supplier Name: ' || coalesce(CAST(sc.s_name AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(sc.s_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(sc.s_comment AS VARCHAR), '') AS vitem FROM joined j JOIN supplier_src sc ON sc.s_suppkey = j.ps_suppkey;
SELECT pairs.p_partkey, pairs.p_name, pairs.p_type, pairs.p_brand, pairs.ps_suppkey, pairs.s_name, pairs.s_acctbal, pairs.s_comment, pairs.nation_name, pairs.region_name, pairs.ps_availqty, pairs.ps_supplycost, pairs.l_orderkey, pairs.l_quantity, pairs.l_extendedprice, pairs.o_orderdate, pairs.o_orderpriority, pairs.o_totalprice, supplier_src.s_suppkey, supplier_src.s_address, supplier_src.s_nationkey, supplier_src.s_phone FROM pairs JOIN supplier_src ON supplier_src.s_suppkey = pairs.ps_suppkey WHERE NLfilter(supplier_src.item_supplier_src, 'You are shortlisting suppliers for long-term procurement partnerships. Based on supplier identity style, account balance, and profile comment tone, does this supplier appear commercially dependable enough for preferred-vendor consideration? If uncertain, answer YES.') AND NLfilter(pairs.vitem, 'You are validating whether this supplier profile is suitable for preferred-vendor sourcing. If uncertain, answer YES.');
