-- Q28: our ThalamusDB formulation of swan_queries/Q28.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE orders_src AS SELECT o.o_orderkey, o.o_orderpriority, o.o_totalprice, o.o_comment, o.o_orderdate, o.o_custkey, 'Order Priority: ' || coalesce(CAST(o.o_orderpriority AS VARCHAR), '') || E'\n' || 'Total Price: ' || coalesce(CAST(o.o_totalprice AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(o.o_comment AS VARCHAR), '') AS item_orders_src FROM orders o WHERE o.o_orderdate >= DATE '1995-01-01' AND o.o_orderdate < DATE '1996-07-01' AND o.o_totalprice BETWEEN 100000 AND 220000 AND o.o_orderstatus = 'O' AND o.o_orderpriority IN ('1-URGENT', '2-HIGH');
CREATE TABLE order_focus AS SELECT orders_src.o_orderkey, orders_src.o_orderpriority, orders_src.o_totalprice, orders_src.o_comment, orders_src.o_orderdate, orders_src.o_custkey FROM orders_src WHERE NLfilter(orders_src.item_orders_src, 'Does this order look operationally significant based on priority label, total price, and comment content? If uncertain, answer YES.');
CREATE TABLE lineitem_filtered AS SELECT l.l_orderkey, l.l_partkey, l.l_suppkey, l.l_quantity, l.l_extendedprice, l.l_discount, l.l_shipmode, l.l_shipdate FROM lineitem l WHERE l.l_shipdate >= DATE '1995-01-01' AND l.l_shipdate < DATE '1996-07-01' AND l.l_quantity BETWEEN 18 AND 26 AND l.l_discount BETWEEN 0.04 AND 0.07 AND l.l_shipmode IN ('AIR', 'REG AIR');
CREATE TABLE joined AS SELECT of.o_orderkey, of.o_orderpriority, of.o_totalprice, of.o_comment, of.o_orderdate, of.o_custkey, lf.l_partkey, lf.l_suppkey, lf.l_quantity, lf.l_extendedprice, lf.l_discount, lf.l_shipmode FROM order_focus of JOIN lineitem_filtered lf ON lf.l_orderkey = of.o_orderkey;
CREATE TABLE customer_src AS SELECT c.c_custkey, c.c_name, c.c_address, c.c_nationkey, c.c_phone, c.c_acctbal, c.c_mktsegment, c.c_comment, 'Customer Name: ' || coalesce(CAST(c.c_name AS VARCHAR), '') || E'\n' || 'Market Segment: ' || coalesce(CAST(c.c_mktsegment AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(c.c_acctbal AS VARCHAR), '') AS item_customer_src FROM customer c JOIN (SELECT DISTINCT o_custkey FROM joined LIMIT 60) k ON k.o_custkey = c.c_custkey;
CREATE TABLE pairs AS SELECT j.*, 'Order Priority: ' || coalesce(CAST(j.o_orderpriority AS VARCHAR), '') || E'\n' || 'Order Total Price: ' || coalesce(CAST(j.o_totalprice AS VARCHAR), '') || E'\n' || 'Lineitem Ship Mode: ' || coalesce(CAST(j.l_shipmode AS VARCHAR), '') || E'\n' || 'Customer Name: ' || coalesce(CAST(cc.c_name AS VARCHAR), '') || E'\n' || 'Market Segment: ' || coalesce(CAST(cc.c_mktsegment AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(cc.c_acctbal AS VARCHAR), '') AS vitem FROM joined j JOIN customer_src cc ON cc.c_custkey = j.o_custkey;
SELECT pairs.o_orderkey, pairs.o_orderpriority, pairs.o_totalprice, pairs.o_comment, pairs.o_orderdate, pairs.o_custkey, pairs.l_partkey, pairs.l_suppkey, pairs.l_quantity, pairs.l_extendedprice, pairs.l_discount, pairs.l_shipmode, customer_src.c_custkey, customer_src.c_name, customer_src.c_address, customer_src.c_nationkey, customer_src.c_phone, customer_src.c_acctbal, customer_src.c_mktsegment, customer_src.c_comment FROM pairs JOIN customer_src ON customer_src.c_custkey = pairs.o_custkey WHERE NLfilter(customer_src.item_customer_src, 'Does this customer look operationally strategic based on name style, market segment, and account balance? If uncertain, answer YES.') AND NLfilter(pairs.vitem, 'Could this customer account be strategically important for order fulfillment? If uncertain, answer YES.');
