-- Q29: our ThalamusDB formulation of swan_queries/Q29.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE partsupp_base AS SELECT ps.ps_partkey, ps.ps_suppkey, ps.ps_availqty, ps.ps_supplycost FROM partsupp ps WHERE ps.ps_availqty BETWEEN 1600 AND 3200 AND ps.ps_supplycost BETWEEN 200 AND 420;
CREATE TABLE supplier_base AS SELECT s.s_suppkey, s.s_name, s.s_address, s.s_acctbal, s.s_comment, s.s_nationkey, n.n_name AS supplier_nation_name, r.r_name AS supplier_region_name FROM supplier s JOIN nation n ON n.n_nationkey = s.s_nationkey JOIN region r ON r.r_regionkey = n.n_regionkey JOIN (SELECT DISTINCT ps_suppkey FROM partsupp_base LIMIT 70) k ON k.ps_suppkey = s.s_suppkey WHERE s.s_acctbal BETWEEN 2000 AND 8000 AND r.r_name IN ('EUROPE', 'ASIA', 'AMERICA');
CREATE TABLE joined AS SELECT sb.s_suppkey, sb.s_name, sb.s_address, sb.s_acctbal, sb.s_comment, sb.s_nationkey, sb.supplier_nation_name, sb.supplier_region_name, pb.ps_partkey, pb.ps_availqty, pb.ps_supplycost FROM supplier_base sb JOIN partsupp_base pb ON pb.ps_suppkey = sb.s_suppkey;
CREATE TABLE semantic_candidates AS SELECT j.s_suppkey, j.s_nationkey, MIN(j.s_acctbal) AS s_acctbal, MIN(j.ps_supplycost) AS ps_supplycost, MIN(j.supplier_region_name) AS supplier_region_name FROM joined j GROUP BY j.s_suppkey, j.s_nationkey LIMIT 50;
CREATE TABLE nation_context AS SELECT ns.n_nationkey, ns.n_name, ns.n_regionkey, ns.n_comment, r.r_regionkey, r.r_name, r.r_comment FROM nation ns JOIN region r ON r.r_regionkey = ns.n_regionkey JOIN (SELECT DISTINCT s_nationkey FROM semantic_candidates ORDER BY s_nationkey LIMIT 5) k ON k.s_nationkey = ns.n_nationkey;
CREATE TABLE pairs AS SELECT j.s_suppkey, j.s_name, j.s_address, j.s_acctbal, j.s_comment, j.s_nationkey, j.supplier_nation_name, j.supplier_region_name, j.ps_partkey, j.ps_availqty, j.ps_supplycost, nc.n_nationkey AS context_nationkey, nc.n_name AS context_nation_name, nc.n_regionkey AS context_regionkey, nc.r_regionkey AS context_region_id, nc.r_name AS context_region_name, nc.n_comment AS context_nation_comment, nc.r_comment AS context_region_comment, 'Supplier Account Balance: ' || coalesce(CAST(sc.s_acctbal AS VARCHAR), '') || E'\n' || 'Supply Cost: ' || coalesce(CAST(sc.ps_supplycost AS VARCHAR), '') || E'\n' || 'Supplier Region: ' || coalesce(CAST(sc.supplier_region_name AS VARCHAR), '') || E'\n' || 'Nation Name: ' || coalesce(CAST(nc.n_name AS VARCHAR), '') || E'\n' || 'Region Name: ' || coalesce(CAST(nc.r_name AS VARCHAR), '') AS vitem FROM joined j JOIN semantic_candidates sc ON sc.s_suppkey = j.s_suppkey AND sc.s_nationkey = j.s_nationkey JOIN nation_context nc ON nc.n_nationkey = sc.s_nationkey;
SELECT pairs.s_suppkey, pairs.s_name, pairs.s_address, pairs.s_acctbal, pairs.s_comment, pairs.s_nationkey, pairs.supplier_nation_name, pairs.supplier_region_name, pairs.ps_partkey, pairs.ps_availqty, pairs.ps_supplycost, pairs.context_nationkey, pairs.context_nation_name, pairs.context_regionkey, pairs.context_region_id, pairs.context_region_name, pairs.context_nation_comment, pairs.context_region_comment FROM pairs WHERE NLfilter(pairs.vitem, 'Does this sourcing region align with procurement priorities? If uncertain, answer YES.');
