"""Shared scoring for SemBench MOVIE (sf_2000) -- faithful port of SemBench's MovieEvaluator semantics.

Per-query metric (from src/scenario/movie/evaluation/evaluate.py):
  q1,q2   retrieval WITH limit 5   -> precision over returned ids (validity), limit-aware recall, f1
  q3,q4   single-value aggregation -> relative error; quality = max(0, 1 - rel_err)
  q5,q6   review PAIRS with limit 10 -> normalized (movie, sorted(reviewId pair)) sets, limit-aware recall, f1
  q7      review PAIRS, no limit   -> plain set precision/recall/f1
  q8      sentiment counts         -> mean relative error over POSITIVE/NEGATIVE; quality = max(0, 1 - rel_err)
  q9,q10  ranking (id, score)      -> Spearman rho on common ids (quality); kendall tau-b also reported

Ground truth: gold/qN.csv generated by gen_ground_truth.py from queries/gold_sql (exact relational SQL over
the Reviews/Movies CSVs -- the data carries gold scoreSentiment labels and Movies.audienceScore).

All metrics are pure python (no scipy/pandas) so both runner envs can import this.
"""
import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))

LIMIT_QUERIES = {"q1": 5, "q2": 5, "q5": 10, "q6": 10}
PAIR_QUERIES = {"q5", "q6", "q7"}
AGG_QUERIES = {"q3", "q4"}
RANK_QUERIES = {"q9", "q10"}


def gt(name):
    """Load gold/qN.csv -> list of row tuples (strings, header skipped)."""
    p = os.path.join(HERE, "gold", name + ".csv")
    with open(p) as f:
        rows = list(csv.reader(f))
    return [tuple(r) for r in rows[1:]]


def _pair_key(row):
    movie, a, b = row[0], row[1], row[2]
    return (movie, tuple(sorted([a, b])))


def _prf(p, r):
    f = 2 * p * r / (p + r) if (p + r) else 0.0
    return round(p, 3), round(r, 3), round(f, 3)


def _rank_corr(sys_rows, gold_rows):
    """Spearman rho (average ranks for ties) + kendall tau-b over ids common to both."""
    def to_map(rows):
        m = {}
        for r in rows:
            try:
                m[str(r[0])] = float(r[1])
            except (ValueError, IndexError):
                continue
        return m
    s, g = to_map(sys_rows), to_map(gold_rows)
    ids = sorted(set(s) & set(g))
    if len(ids) < 2:
        return 0.0, 0.0
    xs = [s[i] for i in ids]
    ys = [g[i] for i in ids]

    def ranks(v):
        order = sorted(range(len(v)), key=lambda i: v[i])
        rk = [0.0] * len(v)
        i = 0
        while i < len(order):
            j = i
            while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
                j += 1
            avg = (i + j) / 2.0 + 1.0
            for k in range(i, j + 1):
                rk[order[k]] = avg
            i = j + 1
        return rk

    def pearson(a, b):
        n = len(a)
        ma, mb = sum(a) / n, sum(b) / n
        num = sum((a[i] - ma) * (b[i] - mb) for i in range(n))
        da = sum((x - ma) ** 2 for x in a) ** 0.5
        db = sum((x - mb) ** 2 for x in b) ** 0.5
        return num / (da * db) if da > 0 and db > 0 else 0.0

    spearman = pearson(ranks(xs), ranks(ys))

    # kendall tau-b
    n = len(xs)
    concordant = discordant = ties_x = ties_y = 0
    for i in range(n):
        for j in range(i + 1, n):
            dx = xs[i] - xs[j]
            dy = ys[i] - ys[j]
            if dx == 0 and dy == 0:
                ties_x += 1
                ties_y += 1
            elif dx == 0:
                ties_x += 1
            elif dy == 0:
                ties_y += 1
            elif dx * dy > 0:
                concordant += 1
            else:
                discordant += 1
    denom = ((concordant + discordant + ties_x) * (concordant + discordant + ties_y)) ** 0.5
    tau = (concordant - discordant) / denom if denom > 0 else 0.0
    return round(spearman, 3), round(tau, 3)


def score(name, sys_rows, gold_rows):
    """-> (precision, recall, quality) exactly like ecomm_common.score; quality is the headline metric."""
    if name in RANK_QUERIES:
        spearman, tau = _rank_corr(sys_rows, gold_rows)
        return spearman, tau, spearman  # (rho, tau-b, quality=rho)

    if name in AGG_QUERIES:
        # single numeric value, first numeric column of the single row
        def first_num(rows):
            if len(rows) != 1:
                return None
            for v in rows[0]:
                try:
                    return float(v)
                except ValueError:
                    continue
            return None
        sv, gv = first_num(sys_rows), first_num(gold_rows)
        if sv is None or gv is None:
            return 0.0, 1.0, 0.0
        rel = abs(sv - gv) / abs(gv) if gv != 0 else (0.0 if sv == 0 else 1.0)
        return round(sv, 4), round(rel, 4), round(max(0.0, 1.0 - rel), 3)  # (value, rel_err, quality)

    if name == "q8":
        # rows of (sentiment, count); mean relative error across the union of labels
        def to_counts(rows):
            m = {}
            for r in rows:
                try:
                    m[str(r[0]).strip().upper()] = float(r[1])
                except (ValueError, IndexError):
                    continue
            return m
        s, g = to_counts(sys_rows), to_counts(gold_rows)
        if not s or not g:
            return 0.0, 1.0, 0.0
        total_rel, n = 0.0, 0
        for lab in set(s) | set(g):
            sv, gv = s.get(lab, 0.0), g.get(lab, 0.0)
            if gv != 0:
                total_rel += abs(sv - gv) / abs(gv)
                n += 1
            elif sv != 0:
                total_rel += 1.0
                n += 1
        rel = total_rel / n if n else 0.0
        return 0.0, round(rel, 4), round(max(0.0, 1.0 - rel), 3)  # (-, rel_err, quality)

    if name in PAIR_QUERIES:
        limit = LIMIT_QUERIES.get(name)
        sys_use = sys_rows[:limit] if limit else sys_rows
        sp = {_pair_key(r) for r in sys_use if len(r) >= 3}
        gp = {_pair_key(r) for r in gold_rows if len(r) >= 3}
        if not sp:
            return (1.0, 1.0, 1.0) if not gp else (0.0, 0.0, 0.0)
        if not gp:
            return 0.0, 0.0, 0.0
        correct = sp & gp
        p = len(correct) / len(sp)
        if limit:
            r = min(len(correct), limit) / min(limit, len(gp))
        else:
            r = len(correct) / len(gp)
        return _prf(p, r)

    # q1/q2: retrieval with limit over first column
    limit = LIMIT_QUERIES[name]
    sys_use = sys_rows[:limit]
    sids = {r[0] for r in sys_use if r}
    gids = {r[0] for r in gold_rows if r}
    if not sids:
        return (1.0, 1.0, 1.0) if not gids else (0.0, 0.0, 0.0)
    if not gids:
        return 0.0, 0.0, 0.0
    valid = sids & gids
    p = len(valid) / len(sids)
    r = min(len(valid), limit) / min(limit, len(gids))
    return _prf(p, r)
