-- Q18: our ThalamusDB formulation of swan_queries/Q18.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE part_src AS SELECT p_partkey, p_name, p_type, p_container, p_size, 'Part Name: ' || coalesce(CAST(p_name AS VARCHAR), '') || E'\n' || 'Part Type: ' || coalesce(CAST(p_type AS VARCHAR), '') || E'\n' || 'Container: ' || coalesce(CAST(p_container AS VARCHAR), '') || E'\n' || 'Size: ' || coalesce(CAST(p_size AS VARCHAR), '') AS item_part_src FROM part WHERE p_size BETWEEN 3 AND 30 AND p_container IN ('SM BOX', 'SM CASE', 'MED BOX', 'MED BAG', 'LG BOX');
CREATE TABLE lineitem_orders AS SELECT l.l_orderkey, l.l_partkey, l.l_suppkey, l.l_shipmode, l.l_shipinstruct, l.l_quantity, l.l_extendedprice, l.l_discount, o.o_custkey, o.o_orderdate, o.o_orderpriority, o.o_totalprice FROM lineitem l JOIN orders o ON o.o_orderkey = l.l_orderkey WHERE l.l_shipmode IN ('AIR', 'REG AIR', 'TRUCK', 'MAIL') AND l.l_shipinstruct IN ('DELIVER IN PERSON', 'TAKE BACK RETURN') AND l.l_quantity BETWEEN 10 AND 45 AND o.o_orderdate >= DATE '1994-01-01' AND o.o_orderdate < DATE '1998-01-01' AND o.o_totalprice > 30000;
CREATE TABLE customer_geo AS SELECT c.c_custkey, c.c_name, c.c_nationkey, c.c_mktsegment, c.c_acctbal, n.n_name AS customer_nation, r.r_name AS customer_region FROM customer c JOIN nation n ON n.n_nationkey = c.c_nationkey JOIN region r ON r.r_regionkey = n.n_regionkey WHERE r.r_name IN ('AMERICA', 'EUROPE', 'ASIA');
CREATE TABLE nation_src AS SELECT *, 'Nation: ' || coalesce(CAST(n_name AS VARCHAR), '') AS item_nation_src FROM (SELECT * FROM nation LIMIT 25);
SELECT part_src.p_partkey, part_src.p_name, part_src.p_type, part_src.p_container, lo.l_orderkey, lo.l_shipmode, lo.l_shipinstruct, lo.l_quantity, lo.l_extendedprice, lo.l_discount, lo.o_orderdate, lo.o_orderpriority, lo.o_totalprice, cg.c_name, cg.c_mktsegment, cg.c_acctbal, cg.customer_nation, cg.customer_region, nation_src.n_nationkey, nation_src.n_name, nation_src.n_regionkey, nation_src.n_comment FROM part_src JOIN lineitem_orders lo ON lo.l_partkey = part_src.p_partkey JOIN customer_geo cg ON cg.c_custkey = lo.o_custkey, nation_src WHERE NLfilter(part_src.item_part_src, 'You are preparing a logistics performance dashboard for retail distribution. Based on product name, type, packaging container, and size, does this part look like something that would realistically move through customer-facing distribution channels? If uncertain, answer YES.') AND NLfilter(nation_src.item_nation_src, 'You are selecting countries to include in a cross-border freight and trade analysis view. Is this nation likely meaningful enough to keep in a global logistics discussion dataset? If uncertain, answer YES.');
