-- Q21: our ThalamusDB formulation of swan_queries/Q21.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE yelp_business AS SELECT * FROM read_csv_auto('./dataset/yelp/yelp_business_csv/business.csv', maximum_line_size=1048576);
CREATE TABLE yelp_review AS SELECT * FROM read_csv_auto('./dataset/yelp/review.csv', maximum_line_size=1048576);
CREATE TABLE yelp_tip AS SELECT * FROM read_csv_auto('./dataset/yelp/tip.csv', maximum_line_size=1048576);
CREATE TABLE reviews_link AS SELECT 'businessid_' || regexp_extract(r.business_ref, '([0-9]+)$') AS business_id, r.rating, r.date AS review_date FROM yelp_review r WHERE r.business_ref LIKE 'businessref_%';
CREATE TABLE tips_link AS SELECT 'businessid_' || regexp_extract(t.business_ref, '([0-9]+)$') AS business_id, t.date AS tip_date FROM yelp_tip t WHERE t.business_ref LIKE 'businessref_%';
CREATE TABLE yelp_src AS SELECT yb.*, 'Business ID: ' || coalesce(CAST(yb.business_id AS VARCHAR), '') || E'\n' || 'Attributes: ' || coalesce(CAST(yb.attributes AS VARCHAR), '') || E'\n' || 'Description: ' || coalesce(CAST(yb.description AS VARCHAR), '') AS item_yelp_src FROM yelp_business yb;
CREATE TABLE category_tokens AS SELECT n.business_id, lower(trim(tokens.raw_token)) AS category FROM (SELECT s.business_id, regexp_replace(coalesce(regexp_extract(s.description, '(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+(.+?)(?:\.|$)', 1), ''), '^(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+', '') AS raw_categories FROM yelp_src s) n, LATERAL UNNEST(string_split(replace(replace(replace(n.raw_categories, ', and ', ', '), ' and ', ', '), '  ', ' '), ',')) AS tokens(raw_token) WHERE trim(tokens.raw_token) <> '';
SELECT ct.category, yelp_src.business_id, rl.review_date, rl.rating FROM category_tokens ct JOIN yelp_src ON yelp_src.business_id = ct.business_id JOIN reviews_link rl ON rl.business_id = ct.business_id JOIN tips_link tl ON tl.business_id = ct.business_id WHERE yelp_src.attributes ILIKE '%"BusinessAcceptsCreditCards": "True"%' AND rl.review_date ILIKE '%2019%' AND tl.tip_date ILIKE '%2019%' AND NLfilter(yelp_src.item_yelp_src, 'Return true if the business clearly accepts credit card payments. Prefer explicit evidence from attributes or the narrative.') ORDER BY rl.rating DESC, rl.review_date DESC;
