-- Q24: our ThalamusDB formulation of swan_queries/Q24.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE yelp_business AS SELECT * FROM read_csv_auto('./dataset/yelp/yelp_business_csv/business.csv', maximum_line_size=1048576);
CREATE TABLE yelp_review AS SELECT * FROM read_csv_auto('./dataset/yelp/review.csv', maximum_line_size=1048576);
CREATE TABLE yelp_user AS SELECT * FROM read_csv_auto('./dataset/yelp/user.csv', maximum_line_size=1048576);
CREATE TABLE qualified_users AS SELECT user_id FROM (SELECT u.user_id, COALESCE(try_strptime(u.yelping_since, '%Y-%m-%d %H:%M:%S'), try_strptime(u.yelping_since, '%d %b %Y, %H:%M'), try_strptime(u.yelping_since, '%d %b %Y %H:%M'), try_strptime(u.yelping_since, '%d %b %Y, %I:%M %p'), try_strptime(u.yelping_since, '%d %B %Y, %H:%M'), try_strptime(u.yelping_since, '%d %B %Y, %I:%M %p'), try_strptime(u.yelping_since, '%B %d, %Y at %I:%M %p'), try_strptime(u.yelping_since, '%B %d, %Y %H:%M %p'), try_strptime(u.yelping_since, '%d %B %Y at %I:%M %p'), try_strptime(u.yelping_since, '%d %b %Y at %I:%M %p')) AS joined_ts FROM yelp_user u) j WHERE joined_ts BETWEEN TIMESTAMP '2016-01-01 00:00:00' AND TIMESTAMP '2016-12-31 23:59:59';
CREATE TABLE filtered_reviews AS SELECT pr.business_id, pr.user_id, pr.review_ts FROM (SELECT 'businessid_' || regexp_extract(r.business_ref, '([0-9]+)$') AS business_id, r.user_id, COALESCE(try_strptime(r.date, '%Y-%m-%d %H:%M:%S'), try_strptime(r.date, '%d %b %Y, %H:%M'), try_strptime(r.date, '%d %b %Y %H:%M'), try_strptime(r.date, '%d %b %Y, %I:%M %p'), try_strptime(r.date, '%d %B %Y, %H:%M'), try_strptime(r.date, '%d %B %Y, %I:%M %p'), try_strptime(r.date, '%B %d, %Y at %I:%M %p'), try_strptime(r.date, '%B %d, %Y %H:%M %p'), try_strptime(r.date, '%d %B %Y at %I:%M %p'), try_strptime(r.date, '%d %b %Y at %I:%M %p')) AS review_ts FROM yelp_review r WHERE r.business_ref LIKE 'businessref_%') pr JOIN qualified_users qu ON qu.user_id = pr.user_id WHERE pr.review_ts >= TIMESTAMP '2016-01-01 00:00:00' AND pr.review_ts IS NOT NULL;
CREATE TABLE yelp_src AS SELECT yb.*, 'Business ID: ' || coalesce(CAST(yb.business_id AS VARCHAR), '') || E'\n' || 'Attributes: ' || coalesce(CAST(yb.attributes AS VARCHAR), '') || E'\n' || 'Description: ' || coalesce(CAST(yb.description AS VARCHAR), '') AS item_yelp_src FROM yelp_business yb JOIN (SELECT DISTINCT business_id FROM filtered_reviews) ab ON ab.business_id = yb.business_id;
CREATE TABLE category_tokens AS SELECT n.business_id, lower(trim(tokens.raw_token)) AS category FROM (SELECT s.business_id, regexp_replace(coalesce(regexp_extract(s.description, '(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+(.+?)(?:\.|$)', 1), ''), '^(?:services(?: and products)? in|services including|services, including|including|destination for|seeking|specializes in|such as|in the fields of|selection of|range of|array of|variety of|mix of|collection of|menu featuring|options for|dedicated to|catering to)\s+', '') AS raw_categories FROM yelp_src s) n, LATERAL UNNEST(string_split(replace(replace(replace(n.raw_categories, ', and ', ', '), ' and ', ', '), '  ', ' '), ',')) AS tokens(raw_token) WHERE trim(tokens.raw_token) <> '';
SELECT ct.category, fr.user_id, fr.review_ts FROM category_tokens ct JOIN filtered_reviews fr ON fr.business_id = ct.business_id JOIN yelp_src ON yelp_src.business_id = ct.business_id WHERE NLfilter(yelp_src.item_yelp_src, 'Return true if the business description clearly lists multiple categories or service types that can be tokenized. Focus on entries with explicit category phrases.') ORDER BY fr.review_ts DESC;
