-- Q26: our ThalamusDB formulation of swan_queries/Q26.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE customer_src AS SELECT *, 'Customer Name: ' || coalesce(CAST(c_name AS VARCHAR), '') || E'\n' || 'Market Segment: ' || coalesce(CAST(c_mktsegment AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(c_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(c_comment AS VARCHAR), '') AS item_customer_src FROM customer WHERE c_acctbal > 500 AND c_mktsegment IN ('AUTOMOBILE', 'BUILDING', 'MACHINERY');
CREATE TABLE part_src AS SELECT p_partkey, p_name, p_type, p_brand, 'Part Name: ' || coalesce(CAST(p_name AS VARCHAR), '') || E'\n' || 'Part Type: ' || coalesce(CAST(p_type AS VARCHAR), '') || E'\n' || 'Brand: ' || coalesce(CAST(p_brand AS VARCHAR), '') AS item_part_src FROM part;
CREATE TABLE supplier_src AS SELECT s.s_suppkey, s.s_name, s.s_acctbal, s.s_comment, n.n_name AS supplier_nation, r.r_name AS supplier_region, 'Supplier Name: ' || coalesce(CAST(s.s_name AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(s.s_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(s.s_comment AS VARCHAR), '') || E'\n' || 'Nation: ' || coalesce(CAST(n.n_name AS VARCHAR), '') || E'\n' || 'Region: ' || coalesce(CAST(r.r_name AS VARCHAR), '') AS item_supplier_src FROM supplier s JOIN nation n ON n.n_nationkey = s.s_nationkey JOIN region r ON r.r_regionkey = n.n_regionkey WHERE s.s_acctbal > 0;
CREATE TABLE orders_src AS SELECT o.*, 'Order Priority: ' || coalesce(CAST(o.o_orderpriority AS VARCHAR), '') || E'\n' || 'Total Price: ' || coalesce(CAST(o.o_totalprice AS VARCHAR), '') || E'\n' || 'Order Comment: ' || coalesce(CAST(o.o_comment AS VARCHAR), '') AS item_orders_src FROM orders o WHERE o.o_orderstatus = 'O' AND o.o_orderpriority IN ('1-URGENT', '2-HIGH') AND o.o_totalprice > 90000;
CREATE TABLE part_sem AS SELECT * FROM part_src WHERE NLfilter(part_src.item_part_src, 'You are helping a retail analytics team pick products for customer demand analysis. From the name, type, and brand, does this item read like a marketable finished good rather than an upstream industrial input? If uncertain, answer YES.');
CREATE TABLE supplier_sem AS SELECT * FROM supplier_src WHERE NLfilter(supplier_src.item_supplier_src, 'You are shortlisting suppliers for stable operations. Based on supplier name style, account balance, comment, nation, and region, does this supplier look commercially dependable? If uncertain, answer YES.');
CREATE TABLE orders_sem AS SELECT * FROM orders_src WHERE NLfilter(orders_src.item_orders_src, 'You are triaging enterprise orders for operations monitoring. From priority, total price, and comment, should this order be considered operationally important? If uncertain, answer YES.');
CREATE TABLE customer_sem AS SELECT * FROM customer_src WHERE NLfilter(customer_src.item_customer_src, 'You are tagging accounts for B2B revenue analysis. Based on customer name, market segment, account balance, and profile comment, does this customer look business-like and operationally relevant? If uncertain, answer NO.');
SELECT l.l_orderkey, l.l_linenumber, l.l_quantity, l.l_extendedprice, l.l_discount, l.l_tax, l.l_shipmode, l.l_shipinstruct, part_sem.p_name, part_sem.p_type, part_sem.p_brand, supplier_sem.s_name, supplier_sem.supplier_nation, supplier_sem.supplier_region, ps.ps_supplycost, ps.ps_availqty, customer_sem.c_custkey AS context_custkey, customer_sem.c_name, customer_sem.c_mktsegment, customer_sem.c_acctbal FROM lineitem l JOIN orders_sem ON orders_sem.o_orderkey = l.l_orderkey JOIN partsupp ps ON ps.ps_partkey = l.l_partkey AND ps.ps_suppkey = l.l_suppkey JOIN part_sem ON part_sem.p_partkey = l.l_partkey JOIN supplier_sem ON supplier_sem.s_suppkey = l.l_suppkey, customer_sem WHERE l.l_shipdate >= DATE '1995-01-01' AND l.l_shipdate < DATE '1997-01-01' AND l.l_discount BETWEEN 0.05 AND 0.08 AND l.l_quantity BETWEEN 16 AND 24 AND l.l_shipmode IN ('AIR', 'REG AIR') AND l.l_shipinstruct = 'DELIVER IN PERSON' AND ps.ps_supplycost BETWEEN 80 AND 900 AND ps.ps_availqty >= 50;
