-- Q30: our ThalamusDB formulation of swan_queries/Q30.sql (see make_thalamusdb_queries.py for the rule).
-- Statements end with ';' at a line end; thalamusdb_exec.py runs the plain ones as setup, a CREATE TABLE ... AS <select with
-- NLfilter> through ThalamusDB as a stage, and the last statement as the query.
CREATE TABLE part AS SELECT * FROM read_parquet('./dataset/tpch/part.parquet');
CREATE TABLE supplier AS SELECT * FROM read_parquet('./dataset/tpch/supplier.parquet');
CREATE TABLE customer AS SELECT * FROM read_parquet('./dataset/tpch/customer.parquet');
CREATE TABLE lineitem AS SELECT * FROM read_parquet('./dataset/tpch/lineitem.parquet');
CREATE TABLE orders AS SELECT * FROM read_parquet('./dataset/tpch/orders.parquet');
CREATE TABLE partsupp AS SELECT * FROM read_parquet('./dataset/tpch/partsupp.parquet');
CREATE TABLE nation AS SELECT * FROM read_parquet('./dataset/tpch/nation.parquet');
CREATE TABLE region AS SELECT * FROM read_parquet('./dataset/tpch/region.parquet');
CREATE TABLE olc AS SELECT l.l_orderkey, l.l_partkey, l.l_suppkey, l.l_quantity, l.l_extendedprice, l.l_discount, l.l_shipmode, o.o_orderdate, o.o_orderpriority, o.o_totalprice, c.c_custkey, c.c_name, c.c_mktsegment, c.c_acctbal FROM lineitem l JOIN orders o ON o.o_orderkey = l.l_orderkey JOIN customer c ON c.c_custkey = o.o_custkey WHERE l.l_shipmode IN ('AIR', 'REG AIR', 'TRUCK') AND l.l_quantity BETWEEN 12 AND 30 AND l.l_discount BETWEEN 0.04 AND 0.07 AND o.o_orderdate >= DATE '1996-01-01' AND o.o_orderdate < DATE '1998-01-01' AND o.o_totalprice BETWEEN 60000 AND 170000 AND c.c_mktsegment IN ('FURNITURE', 'HOUSEHOLD', 'MACHINERY', 'BUILDING');
CREATE TABLE part_src AS SELECT p.p_partkey, p.p_name, p.p_type, p.p_container, p.p_size, 'Part Name: ' || coalesce(CAST(p.p_name AS VARCHAR), '') || E'\n' || 'Part Type: ' || coalesce(CAST(p.p_type AS VARCHAR), '') || E'\n' || 'Container: ' || coalesce(CAST(p.p_container AS VARCHAR), '') AS item_part_src FROM part p JOIN (SELECT DISTINCT l_partkey FROM olc LIMIT 200) k ON k.l_partkey = p.p_partkey WHERE p.p_size BETWEEN 5 AND 28 AND p.p_container IN ('SM BOX', 'MED BOX', 'LG BOX', 'SM CASE');
CREATE TABLE part_focus AS SELECT part_src.p_partkey, part_src.p_name, part_src.p_type, part_src.p_container, part_src.p_size FROM part_src WHERE NLfilter(part_src.item_part_src, 'Does this part look suitable for customer-facing distribution based on name, type, and packaging? If uncertain, answer YES.');
CREATE TABLE joined AS SELECT pf.p_partkey, pf.p_name, pf.p_type, pf.p_container, olc.l_orderkey, olc.l_suppkey, olc.l_quantity, olc.l_extendedprice, olc.l_discount, olc.l_shipmode, olc.o_orderdate, olc.o_orderpriority, olc.o_totalprice, olc.c_custkey, olc.c_name, olc.c_mktsegment, olc.c_acctbal FROM part_focus pf JOIN olc ON olc.l_partkey = pf.p_partkey;
CREATE TABLE supplier_src AS SELECT s.s_suppkey, s.s_name, s.s_address, s.s_nationkey, s.s_phone, s.s_acctbal, s.s_comment, 'Supplier Name: ' || coalesce(CAST(s.s_name AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(s.s_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(s.s_comment AS VARCHAR), '') AS item_supplier_src FROM supplier s JOIN (SELECT DISTINCT l_suppkey FROM joined LIMIT 40) k ON k.l_suppkey = s.s_suppkey;
CREATE TABLE pairs AS SELECT j.*, 'Part Type: ' || coalesce(CAST(j.p_type AS VARCHAR), '') || E'\n' || 'Ship Mode: ' || coalesce(CAST(j.l_shipmode AS VARCHAR), '') || E'\n' || 'Customer Segment: ' || coalesce(CAST(j.c_mktsegment AS VARCHAR), '') || E'\n' || 'Supplier Name: ' || coalesce(CAST(sc.s_name AS VARCHAR), '') || E'\n' || 'Account Balance: ' || coalesce(CAST(sc.s_acctbal AS VARCHAR), '') || E'\n' || 'Comment: ' || coalesce(CAST(sc.s_comment AS VARCHAR), '') AS vitem FROM joined j JOIN supplier_src sc ON sc.s_suppkey = j.l_suppkey;
SELECT pairs.p_partkey, pairs.p_name, pairs.p_type, pairs.p_container, pairs.l_orderkey, pairs.l_suppkey, pairs.l_quantity, pairs.l_extendedprice, pairs.l_discount, pairs.l_shipmode, pairs.o_orderdate, pairs.o_orderpriority, pairs.o_totalprice, pairs.c_custkey, pairs.c_name, pairs.c_mktsegment, pairs.c_acctbal, supplier_src.s_suppkey, supplier_src.s_name, supplier_src.s_address, supplier_src.s_nationkey, supplier_src.s_phone, supplier_src.s_acctbal, supplier_src.s_comment FROM pairs JOIN supplier_src ON supplier_src.s_suppkey = pairs.l_suppkey WHERE NLfilter(supplier_src.item_supplier_src, 'Does this supplier appear qualified for consumer-facing distribution partnerships? If uncertain, answer YES.') AND NLfilter(pairs.vitem, 'Would this supplier be suitable for retail distribution of this product? If uncertain, answer YES.');
