-- govreport mix queries: 45 boolean ai_filter queries over the `govreport` table.
-- Each query preserves the source expression's order and AND/OR/NOT structure.

-- q0: 2 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary));

-- q1: 2 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary));

-- q2: 2 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary));

-- q3: 2 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary));

-- q4: 2 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary));

-- q5: 3 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary));

-- q6: 3 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)));

-- q7: 3 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary));

-- q8: 3 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)));

-- q9: 3 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary));

-- q10: 4 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)));

-- q11: 4 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)));

-- q12: 4 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary)));

-- q13: 4 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)));

-- q14: 4 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary));

-- q15: 5 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary)));

-- q16: 5 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary))));

-- q17: 5 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary))));

-- q18: 5 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary))));

-- q19: 5 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary))));

-- q20: 6 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) OR (((ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary))));

-- q21: 6 filters
SELECT id FROM govreport WHERE (ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) OR (((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary)));

-- q22: 6 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary))) OR (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)));

-- q23: 6 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary)) AND ((ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary))) OR ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)));

-- q24: 6 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary))));

-- q25: 7 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary)))));

-- q26: 7 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))));

-- q27: 7 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary))) OR ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary));

-- q28: 7 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary))) AND (ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary))) AND (ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)));

-- q29: 7 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary))) OR ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary));

-- q30: 8 filters
SELECT id FROM govreport WHERE (((((ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary));

-- q31: 8 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary))))) OR (ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary)));

-- q32: 8 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary)))));

-- q33: 8 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary)))));

-- q34: 8 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary))) OR ((ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary))));

-- q35: 9 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))) AND ((ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary))) OR ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary)));

-- q36: 9 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary))) AND (((ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary))) OR (ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary)));

-- q37: 9 filters
SELECT id FROM govreport WHERE ((ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary))) AND ((ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary))) OR (ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))));

-- q38: 9 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on education? Answer yes or no for the following government report: ' || summary)) OR (((ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))) AND (ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary)))) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary));

-- q39: 9 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary)))) OR (ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary))));

-- q40: 10 filters
SELECT id FROM govreport WHERE (((((ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on energy or resources? Answer yes or no for the following government report: ' || summary))) AND ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on offical statistics? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary))));

-- q41: 10 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on enconomy? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary))) OR ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary))) OR (ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary) OR ((ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary))));

-- q42: 10 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on status or situation of U.S. citizens? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary))) OR ((ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary))))) OR ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary));

-- q43: 10 filters
SELECT id FROM govreport WHERE (((ai_filter('Does the document claim to invest in certain projects? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on social welfare? Answer yes or no for the following government report: ' || summary)) AND (ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary) OR (ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) OR (ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document claim support for certain issues? Answer yes or no for the following government report: ' || summary)))))) OR (ai_filter('Does the document report on certain policies? Answer yes or no for the following government report: ' || summary) OR ai_filter('Does the document report on military activities? Answer yes or no for the following government report: ' || summary)));

-- q44: 10 filters
SELECT id FROM govreport WHERE ((((ai_filter('Does the document report on private companies, organizations, or businesses? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document express flaws or problems in certain areas? Answer yes or no for the following government report: ' || summary)) AND ai_filter('Does the document report on certain laws or regulations? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on national security? Answer yes or no for the following government report: ' || summary)) OR ((ai_filter('Does the document report on people''s health or medical services? Answer yes or no for the following government report: ' || summary) AND (ai_filter('Does the document report on international relations? Answer yes or no for the following government report: ' || summary) AND ((ai_filter('Does the document report on tax, budget, or public finance? Answer yes or no for the following government report: ' || summary) AND ai_filter('Does the document report on government income or expenditure? Answer yes or no for the following government report: ' || summary)) OR ai_filter('Does the document report on protection of the environment? Answer yes or no for the following government report: ' || summary)))) AND ai_filter('Does the document claim to have certain goals? Answer yes or no for the following government report: ' || summary)));
