#!/usr/bin/env bash
# Pack one platform's aisql.duckdb_extension into a `swan-aisql` wheel tagged py3-none-<platform>.
#
#   python/build_wheel.sh [path/to/aisql.duckdb_extension]      (default: ../build/release/extension/aisql/...)
#
# Needs the pinned duckdb (the `duckdb==` line of pyproject.toml) importable by PYTHON (default python3), plus
# the `build` and `wheel` packages: the pinned engine says which DuckDB build string the binary must carry.
# The binary's footer names the build it was compiled for; the script accepts it when it is that engine's
# version string, or its source commit (what the CI pipeline and a plain local build stamp), re-stamps the
# packaged copy with the engine's own string in the latter case, and refuses anything else. The wheel lands
# in python/dist/; swan_aisql/_build.py records the engine for connect()'s check.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
EXT="${1:-$HERE/../build/release/extension/aisql/aisql.duckdb_extension}"
PYTHON="${PYTHON:-python3}"
[ -f "$EXT" ] || { echo "no extension binary at $EXT" >&2; exit 1; }

PIN="$(sed -n 's/^dependencies = \["duckdb==\([^"]*\)"\]/\1/p' "$HERE/pyproject.toml")"
read -r PLATFORM BUILT_FOR EXT_VERSION < <("$PYTHON" "$HERE/footer.py" "$EXT")
read -r ENGINE SOURCE_ID < <("$PYTHON" - "$PIN" <<'EOF'
import sys
pin = sys.argv[1]
try:
    import duckdb
except ImportError:
    sys.exit(f"the pinned duckdb is not importable: pip install --pre 'duckdb=={pin}'")
if duckdb.__version__ != pin:
    sys.exit(f"installed duckdb {duckdb.__version__} is not the pinned {pin}: pip install --pre 'duckdb=={pin}'")
print(*duckdb.sql("SELECT version(), source_id FROM pragma_version()").fetchone())
EOF
)

case "$PLATFORM" in
  osx_amd64)     TAG=macosx_10_15_x86_64 ;;
  osx_arm64)     TAG=macosx_11_0_arm64 ;;
  linux_amd64)   TAG=manylinux_2_28_x86_64 ;;
  linux_arm64)   TAG=manylinux_2_28_aarch64 ;;
  windows_amd64) TAG=win_amd64 ;;
  windows_arm64) TAG=win_arm64 ;;
  *) echo "no wheel platform tag for DuckDB platform '$PLATFORM'" >&2; exit 1 ;;
esac

PKG="$HERE/swan_aisql"
cp "$EXT" "$PKG/aisql.duckdb_extension"
if [ "$BUILT_FOR" = "$ENGINE" ]; then
  echo "extension built for $ENGINE ($PLATFORM)"
elif [ "${BUILT_FOR#$SOURCE_ID}" != "$BUILT_FOR" ]; then
  "$PYTHON" "$HERE/footer.py" "$PKG/aisql.duckdb_extension" --stamp "$ENGINE" >/dev/null
  echo "extension built from commit $BUILT_FOR = duckdb $PIN ($ENGINE, $PLATFORM); footer re-stamped"
else
  echo "extension was built for DuckDB '$BUILT_FOR', but duckdb==$PIN is $ENGINE (source $SOURCE_ID)" >&2
  exit 1
fi
cat > "$PKG/_build.py" <<EOF
# Generated by build_wheel.sh: the DuckDB build the bundled aisql.duckdb_extension loads into.
DUCKDB_VERSION = "$PIN"
DUCKDB_ENGINE = "$ENGINE"
DUCKDB_SOURCE_ID = "$SOURCE_ID"
DUCKDB_PLATFORM = "$PLATFORM"
EXTENSION_VERSION = "$EXT_VERSION"
EOF

rm -rf "$HERE/dist" "$HERE/build" "$HERE"/*.egg-info
(cd "$HERE" && "$PYTHON" -m build --wheel >/dev/null)  # isolated: build installs setuptools>=77 itself
GENERIC="$(ls "$HERE"/dist/*.whl)"
"$PYTHON" -m wheel tags --python-tag py3 --abi-tag none --platform-tag "$TAG" --remove "$GENERIC" >/dev/null
ls "$HERE"/dist/*.whl
